---
- hosts: centos
  become: true
  tasks:
    - name: Add an environment vaiable
      lineinfile:
        dest: ~/.bash_profile
        regexp: '^ENV_VAR='
        line: "ENV_VAR=JAY_Patel"

    - name: Get the value of the environment variable we just added.
      shell:  'source ~/.bash_profile && echo $ENV_VAR'
      register: foo

    - name: Print the value of the environment variable.
      debug: 
        msg: "The variable is {{ foo.stdout }}"
        
