---
- hosts: centos
  become: true

  tasks:
  - name: Ensure chrony (for time synchronization) is isntalled
    dnf: 
      name: chrony
      status: present

  - name: Ensure chrony is running

    service: 
      name: chronyd
      state: started
      enabled: yes
