---

- hosts: all
  become: true
  tasks:  

  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"


  - name: install updates (Ubuntu)
    apt:
      upgrade: yes
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache packet and php packet
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

#  - name: add php support for apache
#    apt:
#      name: libapache2-mod-php
#      state: latest
#    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: update repository index - Centos
    dnf:
      update_cache: yes
    when: ansible_distribution in ["CentOS"]

  - name: install apache packet - CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["CentOS"]

  - name: httpd service start - CentOS
    service:
      name: httpd 
      state: started
    when: ansible_distribution in ["CentOS"]

  - name: Create firewall rules for apache server  CentOS
    firewalld:
      service: http
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
    when: ansible_distribution in ["CentOS"]


- hosts: db_server
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    dnf:
      name: mariadb
      state:  latest
    when: ansible_distribution == "CentOS"

- hosts: file_server
  become: true
  tasks:
    - install samba package
      package:
        name: samba
        state: latest
