---
- name: local test
  hosts: 127.0.0.1
  gather_facts: false

  tasks: 
    - name: Check the current system date.
      command: date
      register: date

    - name: Print the current date
      debug: 
        var: date.stdout
