---
- name: add host playbook
  hosts: gw
  connection: httpapi
  gather_facts: false
  # Add or delete host object in Check Point management server
  tasks:
    - name: Set new static route
      check_point.gaia.cp_gaia_static_route:
        address: "192.168.35.0"
        mask_length: 24
        type: "gateway"
        next_hop: [{"gateway": "192.168.11.2", "priority": 2}]

